server:
  port: 9200
spring:
    application:
      name: CompulynxTest
    datasource:
      url: jdbc:sqlserver://localhost:1433;databaseName=compulynx;encrypt=true;trustServerCertificate=true
      username: ibrahim
      password: kali
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: false
      properties:
        hibernate:
          format_sql: true
          dialect: org.hibernate.dialect.SQLServerDialect
servlet:
  multipart:
     max-file-size: 5MB
     max-request-size: 5MB
token:
  secret:
    key: qDAVgLXSwGhxyIYJtOd9z3ya1+OPSS4J6MOcvrr/00chNk1lxv5IYZxOLV1L5GgDC8rHfr5aF4ZccK+OcvcYMA==

security:
  jwt:
    expiration-time: 3600000 # 1h in millisecond

files:
  dir:
    upload: /home/ibrahim/applications/API/dataprocessing/

mvc:
  pathmatch:
    matching-strategy: ant_path_matcher
